#
# LOCAL TESTING
#
# Hanya untuk keperluan pengujian lokal
#

networks: 
  net:
    name: moodle_net
    driver: bridge

volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:                    # def: overlay
  mariadb_data_rr:                    # def: overlay
  # prom_data:
  # grafana_data:
  # redis_data:

version: '3.9'
services:
  mariadb_master:
    container_name: mariadb
    image: 'bitnami/mariadb:10.5'
    
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=user
      # - MARIADB_ROOT_USER=root
      # - MARIADB_PASSWORD=pass
      - MARIADB_DATABASE=db
      - MARIADB_SKIP_TEST_DB=yes

      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=master_root_password
    ports: 
      - '3306:3306/tcp'
    volumes: 
      - mariadb_data:/bitnami/mariadb
    networks: 
      - net

  mariadb_readreplica:
    container_name: mariadb_slave
    image: 'bitnami/mariadb:10.5'
    environment: 
      # - MARIADB_USER=user
      # - MARIADB_PASSWORD=pass
      # - MARIADB_DATABASE=db
      - MARIADB_SKIP_TEST_DB=yes
      # - MARIADB_ROOT_USER=root
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mariadb_master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master_root_password        
    ports: 
      - '3307:3306/tcp'
    volumes: 
      - mariadb_data_rr:/bitnami/mariadb
    networks: 
      - net      

  moodle:
    image: andrianovsky/moodle-3.11.2:latest
    container_name: moodle
    ports:
      - '80:8080'
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=user@student.com
      - MOODLE_SITE_NAME=Moodle Test Site

      - MOODLE_DATABASE_HOST=mariadb_master
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=db                   
      - MOODLE_DATABASE_USER=user
      # - MOODLE_DATABASE_PASSWORD=user123!
      - ALLOW_EMPTY_PASSWORD=yes

      - PHP_UPLOAD_MAX_FILESIZE=2048M
      - PHP_POST_MAX_SIZE=1024M
      - PHP_MAX_EXECUTION_TIME=120
      
      - MOODLE_SKIP_BOOTSTRAP=no                          # tidak skip ketika membuat database pertama kali
      - MOODLE_SKIP_INSTALL=yes                           # skip instal database jika existed
      - BITNAMI_DEBUG=true
    volumes:
      - /etc/localtime:/etc/localtime
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
      - ./moodle/config.php:/bitnami/moodle/config.php
    networks: 
      - net
    restart: always

  prometheus:
    container_name: prometheus_metric
    image: prom/prometheus:v2.29.2
    ports:
      - 9090:9090
    # environment:
    volumes: 
     - ./configs/prometheus:/etc/prometheus
    #  - prom_data:/prometheus
    networks: 
      - net

  node_exporter:
    container_name: node_exporter
    ports: 
      - 9100:9100
    image: prom/node-exporter:v1.2.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
    restart: unless-stopped
    # network_mode: host
    networks: 
      - net

  grafana:
    container_name: grafana_monitor
    image: grafana/grafana:8.1.2
    ports: 
      - 3000:3000
    volumes:
      # - grafana_data:/var/lib/grafana
      - ./configs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks: 
      - net

  # redis:
  #   container_name: redis_test
  #   image: bitnami/redis:6.0.15
  #   ports: 
  #     - 6379:6379
  #   environment: 
  #     - ALLOW_EMPTY_PASSWORD=yes
    # volumes: 
    #   - redis_data:/bitnami/redis/data  