version: '3.7'
services:
  moodle:
    image: andrianovsky/moodle-bitnami-3.11.2-env:latest
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
      - MOODLE_EMAIL=user@student.id
      - MOODLE_SITE_NAME=Moodle Test Site

      - MOODLE_DATABASE_HOST=rdsmoodletest.chngnw3p2ako.us-east-1.rds.amazonaws.com
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=rds_moodle                   
      - MOODLE_DATABASE_USER=user
      - MOODLE_DATABASE_PASSWORD=user123!
      - ALLOW_EMPTY_PASSWORD=yes

      - PHP_UPLOAD_MAX_FILESIZE=2048M
      - PHP_POST_MAX_SIZE=1024M
      - PHP_MAX_EXECUTION_TIME=120
      
      - MOODLE_SKIP_BOOTSTRAP=no                          # tidak skip ketika membuat database pertama kali
      - MOODLE_SKIP_INSTALL=yes                           # skip instal database jika existed
      - BITNAMI_DEBUG=true
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
      
volumes:                    # def: overlay
  moodle_data:
  moodledata_data: