apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  # - name: MySQL
  #   type: mysql
  #   access: proxy
  #   orgId: 1
  #   url: http://rds____:9090
  #   url: http://mariadb:9090
  #   basicAuth: false
  #   isDefault: true
  #   editable: true