version: '3.7'

services:
  moodle:
    container_name: moodle
    image: andrianovsky/alpine-moodle_3.11:latest         # erseco/alpine-moodle
    ports:
      - '80:8080'
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=rds-moodle.c0jycdiknw8b.us-east-1.rds.amazonaws.com
      - DB_PORT=3306
      - DB_NAME=db_moodle
      - DB_USER=user
      - DB_PASS=user123!
      - SITE_URL=http://${PUBLIC_DNS}
      - MOODLE_SITENAME=Moodle-Test-Site
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin123
    restart: always