version: '3.7'

services:
  moodle:
    container_name: moodle
    image: andrianovsky/alpine-moodle_3.11:latest         # erseco/alpine-moodle
    ports:
      - '80:8080'
    environment:
      - DB_TYPE=mariadb
      - DB_HOST=${RDS_ENDPOINT}
      - DB_PORT=3306
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SITE_URL=http://${PUBLIC_DNS}
      - MOODLE_SITENAME=Moodle-Test-Site
      - MOODLE_USERNAME=${MOD_USER}
      - MOODLE_PASSWORD=${MOD_PASS}
    restart: always